import re
import shutil
from pathlib import Path
from collections import defaultdict
from datetime import datetime
import json
import hashlib
from colorama import init, Fore, Style
from tqdm import tqdm

# Initialize colorama
init(autoreset=True)

# ============================================================
# 🌐 Language Settings
# ============================================================

class LanguageManager:
    """Translation manager between Arabic and English"""

    TRANSLATIONS = {
        'en': {
            'found_files': "📂 Found {} Markdown files",
            'existing_files': "📁 Existing files: {}",
            'checking_files': "⏳ Checking for new files...",
            'no_new_files': "✨ No new files to add!",
            'all_files_exist': "📁 All files ({}) already exist in the repository",
            'found_new_files': "✅ Found {} new files",
            'processing': "⏳ Processing and classifying...",
            'saving_data': "💾 Saving data...",
            'updated_json': "✅ Updated JSON: {}",
            'updating_html': "🌐 Updating HTML report...",
            'updated_html': "✅ Updated HTML: {}",
            'no_data_for_html': "❌ No data to display in report",
            'session_stats': "📊 Session Statistics:",
            'total_source_files': "📄 Total source files: {}",
            'existing_files_count': "📁 Existing files: {}",
            'files_added': "✅ Files added: {}",
            'duplicate_groups': "🔄 Duplicate groups: {}",
            'logged_to': "📝 Logged to: {}",
            'duplicate_files': "Duplicate files:",
            'copies': "copies",
            'unclassified_files': "⚠️ Unclassified files ({}):",
            'reasons': "└─ {}",
            'proposed_category': "└─ Proposed category: {}",
            'more_items': "... and {} more",
            'logged_to_unclassified': "📝 Logged to: {}",
            'check_full_details': "💡 Open the file to see full details",
            'successfully_added': "✨ Successfully added {} files!",
            'duplicate_warning': "⚠️ Found {} duplicate groups",
            'unclassified_warning': "⚠️ Found {} unclassified files",
            'check_unclassified': "📋 Check {} to classify them manually",
            'line': "=" * 60,
            'deleting_old_data': "⚠️ Deleting old data file...",
            'error_reading': "❌ Error reading {}: {}",
            'error_processing': "❌ Error processing {}: {}",
            'no_skill_found': "No skill name found in file, using fallback name: {}",
            'no_category_found': "No main category found",
            'no_subcategory_found': "No sub-category found in {}",
            'processing_success': "✅ Successfully processed: {}",
            'copying_file': "📄 Copying file: {}",
            'no_technology_found': "No specific technology found, using 'general'",
            'unclassified_title': "# 📋 Unclassified Files",
            'unclassified_desc': "These files were not automatically classified. Please review and classify them manually.",
            'file_header': "## 📄 {}",
            'timestamp': "- **⏰ Date**: {}",
            'skill_name': "- **🏷️ Skill Name**: {}",
            'classification_issue': "- **⚠️ Classification Issue**: {}",
            'proposed_main': "- **📂 Proposed Category**: {}",
            'proposed_sub': "- **📁 Proposed Sub-category**: {}",
            'proposed_tech': "- **🔧 Proposed Technology**: {}",
            'additional_details': "- **📝 Additional Details**: {}",
            'required_action': "- **💡 Required Action**: Please review and classify this file manually",
            'duplicates_title': "# 📋 Duplicate Files Report",
            'duplicates_desc': "This is a list of duplicate files that were detected.",
            'session_header': "## 🕐 Session {}",
            'new_files_count': "**New files**: {}",
            'duplicate_groups_count': "**Duplicate groups**: {}",
            'duplicate_item': "### 📄 {}",
            'skill_name_item': "- **Skill Name**: {}",
            'copies_count': "- **Number of copies**: {}",
            'duplicate_list': "- **Duplicate files**:",
            'html_title': "📚 Skills Repository",
            'html_subtitle': "Professional Bilingual Report with Dark Glassmorphism Design",
            'total_skills': "Total Skills",
            'total_categories': "Main Specializations",
            'total_files': "Processed Files",
            'last_updated': "Last Updated",
            'search_placeholder': "🔍 Search for a skill...",
            'no_results': "❌ No results match your search",
            'footer': "This report was automatically generated by the Skill Classification System",
            'toggle_language': "🌐 Language",
            'skills_count': "skill",
            'no_description': "No description",
            'file_label': "📄",
            'technology_label': "⚡ Technology",
            'general_tech': "General",
        },
        'ar': {
            'found_files': "📂 تم العثور على {} ملف Markdown",
            'existing_files': "📁 الملفات الموجودة: {}",
            'checking_files': "⏳ جاري التحقق من الملفات الجديدة...",
            'no_new_files': "✨ لا توجد ملفات جديدة للإضافة!",
            'all_files_exist': "📁 جميع الملفات ({}) موجودة بالفعل في المستودع",
            'found_new_files': "✅ تم العثور على {} ملف جديد",
            'processing': "⏳ جاري المعالجة والتصنيف...",
            'saving_data': "💾 جاري حفظ البيانات...",
            'updated_json': "✅ تم حفظ JSON: {}",
            'updating_html': "🌐 جاري تحديث تقرير HTML...",
            'updated_html': "✅ تم تحديث HTML: {}",
            'no_data_for_html': "❌ لا توجد بيانات لعرضها في التقرير",
            'session_stats': "📊 إحصائيات الجلسة:",
            'total_source_files': "📄 إجمالي الملفات في المصدر: {}",
            'existing_files_count': "📁 الملفات الموجودة: {}",
            'files_added': "✅ الملفات المضافة: {}",
            'duplicate_groups': "🔄 المجموعات المكررة: {}",
            'logged_to': "📝 تم التسجيل في: {}",
            'duplicate_files': "الملفات المكررة:",
            'copies': "نسخ",
            'unclassified_files': "⚠️ الملفات غير المصنفة ({}):",
            'reasons': "└─ {}",
            'proposed_category': "└─ التصنيف المقترح: {}",
            'more_items': "... و {} أكثر",
            'logged_to_unclassified': "📝 تم التسجيل في: {}",
            'check_full_details': "💡 افتح الملف لرؤية التفاصيل الكاملة",
            'successfully_added': "✨ تمت إضافة {} ملف بنجاح!",
            'duplicate_warning': "⚠️ تم العثور على {} مجموعة مكررة",
            'unclassified_warning': "⚠️ تم العثور على {} ملف غير مصنف",
            'check_unclassified': "📋 راجع {} لتصنيفها يدوياً",
            'line': "=" * 60,
            'deleting_old_data': "⚠️ حذف ملف البيانات القديم...",
            'error_reading': "❌ خطأ في قراءة {}: {}",
            'error_processing': "❌ خطأ في معالجة {}: {}",
            'no_skill_found': "لم يتم العثور على اسم مهارة في الملف، سيتم استخدام الاسم الاحتياطي: {}",
            'no_category_found': "لم يتم العثور على تصنيف رئيسي",
            'no_subcategory_found': "لم يتم العثور على تصنيف فرعي في {}",
            'processing_success': "✅ تمت معالجة بنجاح: {}",
            'copying_file': "📄 جاري نسخ الملف: {}",
            'no_technology_found': "لم يتم العثور على تقنية محددة، سيتم استخدام 'عام'",
            'unclassified_title': "# 📋 الملفات غير المصنفة",
            'unclassified_desc': "هذه الملفات لم يتم تصنيفها تلقائياً. يرجى مراجعتها وتصنيفها يدوياً.",
            'file_header': "## 📄 {}",
            'timestamp': "- **⏰ التاريخ**: {}",
            'skill_name': "- **🏷️ اسم المهارة**: {}",
            'classification_issue': "- **⚠️ مشكلة التصنيف**: {}",
            'proposed_main': "- **📂 التصنيف المقترح**: {}",
            'proposed_sub': "- **📁 التصنيف الفرعي المقترح**: {}",
            'proposed_tech': "- **🔧 التقنية المقترحة**: {}",
            'additional_details': "- **📝 تفاصيل إضافية**: {}",
            'required_action': "- **💡 الإجراء المطلوب**: يرجى مراجعة وتصنيف هذا الملف يدوياً",
            'duplicates_title': "# 📋 تقرير الملفات المكررة",
            'duplicates_desc': "هذه قائمة بالملفات المكررة التي تم اكتشافها.",
            'session_header': "## 🕐 جلسة {}",
            'new_files_count': "**الملفات الجديدة**: {}",
            'duplicate_groups_count': "**المجموعات المكررة**: {}",
            'duplicate_item': "### 📄 {}",
            'skill_name_item': "- **اسم المهارة**: {}",
            'copies_count': "- **عدد النسخ**: {}\n",
            'duplicate_list': "- **الملفات المكررة**:",
            'html_title': "📚 مستودع المهارات",
            'html_subtitle': "تقرير عربي ثنائي اللغة بتصميم دارك مود وزجاجي احترافي",
            'total_skills': "إجمالي المهارات",
            'total_categories': "التخصصات الرئيسية",
            'total_files': "الملفات المعالجة",
            'last_updated': "تاريخ التحديث",
            'search_placeholder': "🔍 ابحث عن مهارة ...",
            'no_results': "❌ لا توجد نتائج مطابقة للبحث",
            'footer': "تم إنشاء هذا التقرير تلقائياً بواسطة نظام تصنيف المهارات",
            'toggle_language': "🌐 اللغة",
            'skills_count': "مهارة",
            'no_description': "لا يوجد وصف",
            'file_label': "📄",
            'technology_label': "⚡ التقنية",
            'general_tech': "عام",
        }
    }

    def __init__(self, language='en'):
        self.language = language

    def get(self, key, *args):
        if self.language in self.TRANSLATIONS:
            translation = self.TRANSLATIONS[self.language].get(key, key)
            if args:
                return translation.format(*args)
            return translation
        return key

    def set_language(self, language):
        if language in self.TRANSLATIONS:
            self.language = language
            return True
        return False

    def toggle(self):
        self.language = 'en' if self.language == 'ar' else 'ar'
        return self.language


# ============================================================
# 📁 Define Directories
# ============================================================

SOURCE_DIR = Path(r"slills")
OUTPUT_DIR = Path("sorted_skills")
DATA_FILE = OUTPUT_DIR / "skills_data.json"
UNCLASSIFIED_FILE = OUTPUT_DIR / "unclassified.md"
DUPLICATES_FILE = OUTPUT_DIR / "duplicates_report.md"
SIGNATURES_FILE = OUTPUT_DIR / "file_signatures.json"

# ============================================================
# 🌐 Initialize Language Manager — English by default
# ============================================================

lang = LanguageManager('en')

# ============================================================
# 🌐 Main Categories and Sub-categories
# ============================================================

MAIN_CATEGORIES_ORDER = [
    "Web Development",
    "Mobile Development",
    "AI & Machine Learning",
    "Blockchain",
    "DevOps",
    "Design",
    "Data",
    "WordPress",
    "Finance",
    "Programming Languages",
    "Databases",
    "Cloud & Infrastructure",
    "Security",
    "Game Development",
    "Networking",
    "General Skills",
    "Marketing"
]


MAIN_CATEGORIES_AR = {
    "Web Development": "🌐 تطوير الويب",
    "Mobile Development": "📱 تطوير التطبيقات",
    "AI & Machine Learning": "🧠 الذكاء الاصطناعي",
    "Blockchain": "⛓️ البلوكتشين",
    "DevOps": "⚙️ ديف أوبس",
    "Design": "🎨 التصميم",
    "Data": "📊 البيانات",
    "WordPress": "📝 ووردبريس",
    "Finance": "💰 المالية",
    "Programming Languages": "💻 لغات البرمجة",
    "Databases": "🗄️ قواعد البيانات",
    "Cloud & Infrastructure": "☁️ السحابة والبنية التحتية",
    "Security": "🔐 الأمن السيبراني",
    "Game Development": "🎮 تطوير الألعاب",
    "Networking": "🌐 الشبكات",
    "General Skills": "🎯 المهارات العامة",
    "Marketing": "📣 التسويق"
}

MAIN_CATEGORIES_EN = {
    "Web Development": "🌐 Web Development",
    "Mobile Development": "📱 Mobile Development",
    "AI & Machine Learning": "🧠 AI & Machine Learning",
    "Blockchain": "⛓️ Blockchain",
    "DevOps": "⚙️ DevOps",
    "Design": "🎨 Design",
    "Data": "📊 Data",
    "WordPress": "📝 WordPress",
    "Finance": "💰 Finance",
    "Programming Languages": "💻 Programming Languages",
    "Databases": "🗄️ Databases",
    "Cloud & Infrastructure": "☁️ Cloud & Infrastructure",
    "Security": "🔐 Security",
    "Game Development": "🎮 Game Development",
    "Networking": "🌐 Networking",
    "General Skills": "🎯 General Skills",
    "Marketing": "📣 Marketing"
}


def get_category_name(category_key):
    if lang.language == 'ar':
        return MAIN_CATEGORIES_AR.get(category_key, category_key)
    return MAIN_CATEGORIES_EN.get(category_key, category_key)


MAIN_CATEGORY_KEYWORDS = {
    "Web Development": [
        "react", "nextjs", "next.js", "vue", "vuejs", "angular", "svelte", "sveltekit",
        "html", "css", "scss", "sass", "less", "javascript", "typescript",
        "frontend", "backend", "fullstack", "full-stack",
        "api", "rest", "restful", "graphql", "grpc", "http", "https", "webhook",
        "express", "fastapi", "hono", "elysia", "nestjs", "koa", "fastify",
        "nodejs", "node.js", "deno", "bun",
        "django", "flask", "spring", "springboot", "laravel", "symfony", "rails",
        "web", "browser", "dom", "spa", "ssr", "ssg", "pwa",
        "tailwind", "tailwindcss", "bootstrap", "shadcn", "radix", "chakra",
        "material-ui", "ant-design", "mantine",
        "web-design", "ui", "ux", "responsive", "accessibility", "wcag",
        "vite", "webpack", "rollup", "parcel", "esbuild",
        "astro", "remix", "nuxt", "gatsby", "11ty", "eleventy",
        "storybook", "playwright", "cypress",
        "htmx", "alpinejs", "jquery",
        "compress-images", "image-optimization",
        "auth0", "clerk", "better-auth", "oauth", "jwt", "sso",
        "postman", "newman", "api-testing", "api-docs", "openapi",
        "web-performance", "lighthouse", "core-web-vitals",
        "component-library", "design-system", "figma"
    ],
    "Mobile Development": [
        "android", "ios", "flutter", "react native", "reactnative",
        "kotlin", "swift", "swiftui", "objective-c",
        "mobile", "phone", "tablet", "app", "xcode", "android-studio",
        "ionic", "cordova", "capacitor", "xamarin", "maui",
        "expo", "detox", "fastlane", "app-store", "google-play",
        "push-notification", "deep-link", "in-app-purchase",
        "app-store-connect", "asc", "app-review", "app-rejection",
        "monetization", "paywall", "subscription", "iap",
        "firebase-crashlytics", "app-analytics", "attribution",
        "mobile-testing", "appium", "mobile-security"
    ],
    "AI & Machine Learning": [
        "ai", "llm", "gpt", "gpt-4", "gemini", "claude", "llama", "mistral", "deepseek",
        "openai", "chatgpt", "machine learning", "deep learning",
        "tensorflow", "pytorch", "keras", "scikit-learn", "sklearn",
        "nlp", "rag", "embedding", "vector", "langchain", "llamaindex",
        "huggingface", "agent", "autogen", "crewai", "dspy",
        "neural", "diffusion", "stable-diffusion",
        "computer-vision", "ocr", "speech-recognition",
        "fine-tuning", "lora", "prompt-engineering",
        "composio", "fal-ai", "replicate", "audiocraft",
        "ml-models", "llm-models", "ai-tools", "general-ai",
        "brainstorming", "experiment", "hypothesis", "research",
        "formula-derivation", "proof-checker", "mathematical",
        "scientific-writing", "paper-writing", "literature-review",
        "idea-discovery", "research-pipeline", "experiment-plan",
        "result-to-claim", "citation-audit", "peer-review",
        "ablation-planner", "model-evaluation", "benchmarking",
        "embodiment-description", "figure-spec", "paper-illustration"
    ],
    "Blockchain": [
        "blockchain", "web3", "crypto", "token", "nft",
        "defi", "solidity", "smart contract", "smart-contract",
        "ethereum", "solana", "binance", "polygon",
        "dex", "liquidity", "cairo", "substrate",
        "hardhat", "foundry", "wagmi", "ethers", "viem",
        "bitcoin", "wallet", "metamask", "web3-wallet",
        "tokenomics", "dao", "staking", "yield",
        "crypto-tax", "blockchain-security", "smart-contract-audit",
        "venice", "helius", "jupiter", "okx",
        "binance-api", "trading-signal", "market-rank"
    ],
    "DevOps": [
        "devops", "docker", "compose", "kubernetes", "k8s", "helm",
        "container", "podman",
        "ci/cd", "pipeline", "jenkins", "github-actions", "gitlab-ci", "argocd",
        "monitoring", "observability", "prometheus", "grafana", "datadog",
        "terraform", "pulumi", "ansible",
        "nginx", "apache", "caddy", "traefik",
        "linux", "bash", "shell", "systemd", "sre",
        "infrastructure", "iac", "cloudformation",
        "logging", "fluentd", "elasticsearch", "kibana",
        "sre", "incident-response", "alerting", "on-call",
        "gitops", "flux", "argo", "renovate",
        "security-scanning", "trivy", "grype", "snyk",
        "infrastructure-as-code", "pulumi", "crossplane"
    ],
    "Design": [
        "design", "figma", "sketch", "adobe-xd",
        "prototype", "wireframe", "mockup",
        "graphic", "visual", "brand", "branding", "typography", "logo",
        "animation", "motion-design", "lottie",
        "storybook", "component-library", "design-system",
        "illustrator", "photoshop", "affinity", "canva",
        "ui-design", "ux-design", "user-experience", "user-interface",
        "product-design", "interaction-design", "service-design",
        "design-thinking", "design-sprint", "design-research",
        "color-theory", "layout", "grid", "spacing",
        "accessibility-design", "inclusive-design", "universal-design"
    ],
    "Data": [
        "data", "analytics", "bi", "tableau", "powerbi", "looker",
        "etl", "elt", "data-pipeline", "warehouse",
        "airflow", "kafka", "spark", "bigquery", "snowflake", "dbt",
        "data-science", "pandas", "numpy", "jupyter",
        "seo", "metadata", "structured-data",
        "dataset", "scraping", "web-scraping",
        "data-quality", "data-governance", "data-lineage",
        "statistical-analysis", "eda", "exploratory-data-analysis",
        "data-visualization", "matplotlib", "seaborn", "plotly",
        "machine-learning-data", "ml-data", "training-data",
        "database", "sql", "nosql", "data-warehouse",
        "data-engineering", "data-management", "data-ops"
    ],
    "WordPress": [
        "wordpress", "wp", "plugin", "theme", "gutenberg",
        "wp-block", "wp-rest-api", "wp-interactivity", "wp-cli",
        "woocommerce", "elementor", "acf", "shortcode",
        "wordpress-development", "wp-hooks", "wp-cron",
        "wp-query", "wp-loop", "custom-post-type",
        "wp-security", "wp-optimization", "wp-multisite",
        "wp-headless", "wp-graphql", "wp-json",
        "block-editor", "site-editor", "fse", "full-site-editing"
    ],
    "Finance": [
        "finance", "fintech", "stock", "trading", "investment",
        "forex", "portfolio", "asset-management",
        "stripe", "paypal", "payment-gateway", "billing", "subscription",
        "accounting", "bookkeeping", "tax",
        "financial-reporting", "audit", "compliance",
        "wealth-management", "risk-management", "insurance",
        "crypto-trading", "defi-finance", "yield-farming",
        "corporate-finance", "valuation", "merger",
        "payment-processing", "invoicing", "expense-tracking",
        "budgeting", "forecasting", "financial-modeling"
    ],
    "Programming Languages": [
        "python", "java", "javascript", "typescript", "rust",
        "go", "golang", "c++", "cpp", "c#", "csharp",
        "ruby", "php", "swift", "kotlin", "scala", "elixir",
        "dart", "lua", "julia", "zig", "nim",
        "programming", "coding", "software-development",
        "functional-programming", "oop", "object-oriented",
        "compiler", "interpreter", "language-design",
        "testing", "tdd", "unit-test", "integration-test",
        "package-manager", "dependency-management",
        "code-quality", "linting", "formatting"
    ],
    "Databases": [
        "sql", "postgres", "postgresql", "mysql", "sqlite",
        "mongodb", "dynamodb", "couchdb", "cassandra",
        "redis", "valkey", "memcached",
        "firebase", "firestore", "supabase",
        "database", "db", "orm", "prisma", "drizzle",
        "duckdb", "clickhouse", "pinecone", "weaviate", "chroma",
        "vector-database", "graph-database", "neo4j",
        "data-migration", "schema-design", "query-optimization",
        "replication", "sharding", "partitioning",
        "acid", "transactions", "consistency"
    ],
    "Cloud & Infrastructure": [
        "aws", "ec2", "s3", "lambda", "cloudfront",
        "azure", "azure-functions",
        "gcp", "google cloud", "cloud-run",
        "cloudflare", "cloudflare-workers",
        "serverless", "edge", "cdn",
        "netlify", "vercel", "railway", "render", "fly.io",
        "heroku", "digital-ocean",
        "cloud-computing", "iaas", "paas", "saas",
        "cloud-security", "cloud-monitoring", "cloud-cost",
        "multi-cloud", "hybrid-cloud", "cloud-migration",
        "load-balancing", "auto-scaling", "high-availability",
        "disaster-recovery", "backup", "business-continuity"
    ],
    "Security": [
        "security", "cybersecurity",
        "encryption", "hashing", "tls", "ssl",
        "authentication", "authorization", "auth0",
        "audit", "vulnerability", "penetration", "pentest",
        "jwt", "oauth", "oauth2", "oidc", "saml", "sso",
        "cors", "csrf", "xss", "owasp",
        "clerk", "keycloak", "zero-trust",
        "threat-intelligence", "incident-response", "soc",
        "malware", "ransomware", "phishing", "spoofing",
        "firewall", "ids", "ips", "siem",
        "security-compliance", "gdpr", "hipaa", "pci-dss",
        "security-research", "exploit", "cve", "vulnerability-assessment",
        "forensics", "digital-forensics", "memory-forensics",
        "security-best-practices", "security-architecture",
        "detecting", "hunting", "analysis", "investigation",
        "secure-development", "devsecops", "security-testing"
    ],
    "Game Development": [
        "game", "gamedev", "unity", "unreal", "godot",
        "gaming", "ue4", "ue5", "blueprint",
        "shader", "3d", "2d", "multiplayer", "netcode",
        "webgl", "threejs", "three.js", "phaser",
        "game-design", "game-mechanics", "level-design",
        "game-sound", "game-music", "audio-design",
        "game-ai", "game-physics", "game-animation",
        "mobile-games", "console-games", "pc-games",
        "game-analytics", "game-monetization", "game-engagement"
    ],
    "Networking": [
        "network", "networking", "tcp", "udp", "ip",
        "dns", "routing", "firewall", "vpn",
        "websocket", "webrtc", "socket",
        "http2", "http3", "load-balancer", "reverse-proxy", "istio",
        "network-security", "network-monitoring", "network-analysis",
        "protocol", "ipv4", "ipv6", "subnet",
        "wan", "lan", "vlan", "sd-wan",
        "cdn", "content-delivery", "edge-computing",
        "network-architecture", "network-design", "network-optimization"
    ],
    "General Skills": [
        "writing", "copywriting", "editing", "prose", "grammar",
        "research", "paper", "scientific", "literature", "peer-review",
        "product", "pm", "roadmap", "prd", "strategy",
        "leadership", "management", "executive",
        "education", "training", "teaching",
        "coordination", "team", "communication"
    ],
    "Marketing": [
        "marketing", "brand", "campaign", "funnel", "conversion",
        "seo", "sem", "social-media", "email-marketing", "content",
        "positioning", "messaging", "advertising"
    ]
}


SUB_CATEGORIES = {
    "Web Development": {
        "frontend": {
            "name": "واجهة أمامية",
            "keywords": [
                "react", "nextjs", "next.js", "vue", "vuejs", "nuxt", "angular", "svelte", "sveltekit",
                "astro", "remix", "gatsby", "html", "css", "scss", "sass", "javascript", "typescript",
                "frontend", "ui", "ux", "dom", "spa", "pwa", "ssr", "ssg",
                "tailwind", "tailwindcss", "bootstrap", "shadcn", "radix", "chakra", "mantine",
                "vite", "webpack", "parcel", "esbuild", "htmx", "alpinejs", "jquery",
                "accessibility", "wcag", "responsive", "web-design",
                "framer-motion", "gsap", "storybook", "component-library"
            ]
        },
        "backend": {
            "name": "واجهة خلفية",
            "keywords": [
                "backend", "api", "rest", "restful", "graphql", "grpc", "webhook",
                "express", "fastapi", "nestjs", "koa", "fastify", "hono", "elysia",
                "nodejs", "node.js", "deno", "bun",
                "django", "flask", "spring", "springboot", "laravel", "symfony",
                "rails", "sinatra", "asp.net", "dotnet", "gin", "echo", "go-fiber",
                "http", "https", "middleware", "microservices"
            ]
        },
        "fullstack": {
            "name": "تطوير متكامل",
            "keywords": [
                "fullstack", "full-stack", "full stack",
                "mern", "mean", "t3-stack", "trpc", "monorepo", "turborepo"
            ]
        },
        "testing-web": {
            "name": "اختبار تطبيقات الويب",
            "keywords": [
                "jest", "vitest", "mocha", "chai", "jasmine",
                "playwright", "cypress", "selenium", "puppeteer", "webdriverio",
                "unit-test", "integration-test", "e2e", "tdd", "bdd",
                "test-automation", "newman", "postman"
            ]
        },
        "performance-web": {
            "name": "أداء وتحسين الويب",
            "keywords": [
                "performance", "optimization", "compress", "compress-images",
                "image-optimization", "lighthouse", "web-vitals", "core-web-vitals",
                "lazy-loading", "code-splitting", "tree-shaking", "bundle-analysis"
            ]
        },
        "api-development": {
            "name": "تطوير API",
            "keywords": [
                "openapi", "swagger", "api-docs", "api-design",
                "api-security", "api-gateway", "api-versioning",
                "postman", "newman", "api-testing", "api-mock"
            ]
        },
        "auth-web": {
            "name": "المصادقة على الويب",
            "keywords": [
                "auth0", "clerk", "better-auth", "next-auth",
                "jwt", "oauth", "sso", "authentication-web"
            ]
        },
        "general-web": {
            "name": "ويب عام",
            "keywords": [
                "web-general", "web-dev", "web-tools", "build-in-public",
                "web-standards", "web-fundamentals"
            ]
        }
    },
    "Mobile Development": {
        "android": {
            "name": "أندرويد",
            "keywords": [
                "android", "kotlin", "android-studio", "gradle",
                "jetpack", "jetpack-compose", "room", "workmanager",
                "android-sdk", "apk", "android-security"
            ]
        },
        "ios": {
            "name": "آي أو إس",
            "keywords": [
                "ios", "swift", "swiftui", "uikit", "xcode",
                "cocoa", "objective-c", "combine", "core-data",
                "ios-sdk", "ipa", "ios-security"
            ]
        },
        "flutter": {
            "name": "فلاتر",
            "keywords": ["flutter", "dart", "flutter-web", "flutter-desktop", "flutter-widget"]
        },
        "react-native": {
            "name": "رياكت نايتف",
            "keywords": ["react native", "react-native", "rn", "expo", "detox", "react-navigation"]
        },
        "cross-platform": {
            "name": "متعدد المنصات",
            "keywords": ["ionic", "cordova", "capacitor", "xamarin", "maui", "nativescript"]
        },
        "app-publishing": {
            "name": "نشر التطبيقات",
            "keywords": [
                "asc", "app-store", "app-store-connect", "google-play", "google-play-console",
                "localize-metadata", "fastlane", "in-app-purchase", "wall-submit",
                "app-review", "app-rejection", "app-submission"
            ]
        },
        "mobile-tools": {
            "name": "أدوات الجوال",
            "keywords": [
                "push-notification", "deep-link", "firebase-mobile", "crashlytics",
                "analytics-mobile", "schwartz", "awareness", "mapper",
                "mobile-monetization", "paywall", "subscription-mobile"
            ]
        },
        "mobile-testing": {
            "name": "اختبار التطبيقات",
            "keywords": [
                "appium", "mobile-testing", "detox-mobile",
                "mobile-automation", "testmu"
            ]
        }
    },
    "AI & Machine Learning": {
        "llm-models": {
            "name": "نماذج اللغة الكبيرة",
            "keywords": [
                "gpt", "gpt-4", "gpt-5", "llm", "gemini", "claude", "llama", "mistral", "mixtral", "deepseek",
                "openai", "chatgpt", "anthropic", "cohere", "groq", "ollama",
                "llm-models", "text-generation", "chatbot", "reasoning"
            ]
        },
        "ml-models": {
            "name": "تعلم الآلة",
            "keywords": [
                "machine learning", "ml", "deep learning", "tensorflow", "pytorch",
                "keras", "scikit-learn", "sklearn", "nlp", "rag", "embedding",
                "fine-tuning", "lora", "rlhf", "classification", "neural", "transformer",
                "ml-models", "training", "inference", "model-evaluation"
            ]
        },
        "ai-agents": {
            "name": "وكلاء الذكاء الاصطناعي",
            "keywords": [
                "agent", "autogen", "crewai", "dspy", "langgraph", "swarm",
                "langchain", "llamaindex", "composio", "multi-agent", "tool-calling",
                "ai-agents", "agentic", "autonomous"
            ]
        },
        "computer-vision": {
            "name": "رؤية الحاسوب",
            "keywords": [
                "computer-vision", "vision", "ocr", "object-detection", "yolo",
                "opencv", "stable-diffusion", "diffusion", "fal-ai", "replicate",
                "avatar", "extraction", "image-analysis", "segmentation",
                "sam", "segment-anything", "clip", "blip"
            ]
        },
        "ai-tools": {
            "name": "أدوات الذكاء الاصطناعي",
            "keywords": [
                "huggingface", "prompt-engineering", "prompt",
                "semantic-search", "vector-database", "pinecone",
                "weaviate", "chroma", "qdrant", "milvus",
                "speech-recognition", "text-to-speech", "sentiment-analysis",
                "audiocraft", "musicgen", "audiogen"
            ]
        },
        "general-ai": {
            "name": "ذكاء اصطناعي عام",
            "keywords": [
                "brainstorming", "brainstorm", "experiment", "experiment-plan",
                "hypothesis", "hypothesis-generation", "research", "research-pipeline",
                "literature", "literature-review", "idea-discovery",
                "formula-derivation", "proof-checker", "mathematical",
                "scientific-writing", "paper-writing", "paper-plan",
                "result-to-claim", "citation-audit", "peer-review",
                "ablation-planner", "model-evaluation", "benchmarking",
                "embodiment-description", "figure-spec", "paper-illustration",
                "claim-audit", "novelty-check", "kill-argument",
                "creative-thinking", "research-refine", "research-review"
            ]
        },
        "azure-ai": {
            "name": "أزور للذكاء الاصطناعي",
            "keywords": [
                "azure-ai", "azure-cosmos", "azure-mgmt",
                "azure-servicebus", "document-intelligence", "cognitive-services"
            ]
        },
        "code-analysis": {
            "name": "تحليل الكود",
            "keywords": [
                "semgrep", "rule-creator", "performance-diagnosis",
                "static-analysis", "generic-language", "code-quality",
                "code-review", "code-deduplication", "code-graph"
            ]
        },
        "testing-ai": {
            "name": "اختبار أنظمة الذكاء الاصطناعي",
            "keywords": [
                "acceptance-tests", "qa", "quality-assurance",
                "run-acceptance-tests", "test-automation", "evals",
                "evaluation", "validation", "benchmarking"
            ]
        },
        "async-operations": {
            "name": "العمليات غير المتزامنة",
            "keywords": [
                "parallelize", "async", "asynchronous", "parallel",
                "independent", "async-operations", "concurrency"
            ]
        },
        "config-management": {
            "name": "إدارة التهيئة",
            "keywords": ["mirrord-config", "config", "configuration", "mirrord"]
        },
        "branch-management": {
            "name": "إدارة الفروع",
            "keywords": ["development-branch", "branch", "git-branch", "finishing-branch"]
        }
    },
    "Blockchain": {
        "defi": {
            "name": "التمويل اللامركزي",
            "keywords": [
                "defi", "token", "crypto", "dex", "liquidity", "yield", "staking", "dao",
                "defi-protocols", "lending", "borrowing", "swap"
            ]
        },
        "smart-contracts": {
            "name": "العقود الذكية",
            "keywords": [
                "smart contract", "smart-contract", "solidity", "cairo", "vyper",
                "hardhat", "foundry", "truffle", "erc20", "erc721", "erc1155",
                "smart-contract-audit", "security", "vulnerability-scanner"
            ]
        },
        "web3-frontend": {
            "name": "واجهات Web3",
            "keywords": [
                "wagmi", "ethers", "viem", "web3.js", "metamask", "wallet-connect", "dapp",
                "web3-react", "rainbowkit", "thirdweb"
            ]
        },
        "networks": {
            "name": "شبكات البلوكتشين",
            "keywords": [
                "ethereum", "eth", "solana", "sol", "binance", "bnb",
                "polygon", "matic", "substrate", "near", "aptos", "layer2",
                "bitcoin", "btc", "avalanche", "avax", "fantom", "arbitrum", "optimism"
            ]
        },
        "blockchain-tools": {
            "name": "أدوات البلوكتشين",
            "keywords": [
                "helius", "jupiter", "okx", "venice",
                "binance-api", "trading-signal", "market-rank",
                "token-integration", "token-analyzer"
            ]
        }
    },
    "DevOps": {
        "containerization": {
            "name": "الحاويات",
            "keywords": [
                "docker", "compose", "kubernetes", "k8s", "helm",
                "container", "podman", "dockerfile", "container-registry",
                "docker-swarm", "containerd", "cri-o"
            ]
        },
        "cicd": {
            "name": "التكامل والنشر المستمر",
            "keywords": [
                "ci/cd", "pipeline", "jenkins", "github-actions",
                "gitlab-ci", "circleci", "argocd", "flux", "gitops",
                "azure-devops", "bitbucket-pipelines"
            ]
        },
        "infrastructure": {
            "name": "البنية التحتية كود",
            "keywords": [
                "terraform", "pulumi", "ansible", "chef", "puppet",
                "iac", "cloudformation", "crossplane"
            ]
        },
        "monitoring": {
            "name": "المراقبة والرصد",
            "keywords": [
                "monitoring", "observability", "prometheus", "grafana",
                "datadog", "newrelic", "opentelemetry", "alerting", "sre", "incident",
                "elk", "elasticsearch", "kibana", "logstash",
                "fluentd", "loki", "tempo"
            ]
        },
        "servers": {
            "name": "الخوادم والشبكات",
            "keywords": [
                "nginx", "apache", "caddy", "traefik",
                "linux", "bash", "shell", "systemd", "cron", "ssh",
                "ubuntu", "debian", "centos", "rhel", "alpine"
            ]
        },
        "security-devops": {
            "name": "أمن ديف أوبس",
            "keywords": [
                "devsecops", "security-scanning", "trivy", "grype", "snyk",
                "vulnerability-scanning", "container-security",
                "sast", "dast", "dependency-check"
            ]
        },
        "general-devops": {
            "name": "ديف أوبس عام",
            "keywords": [
                "devops-general", "devops-tools", "devops-best-practices",
                "sre", "reliability", "scalability"
            ]
        }
    },
    "Design": {
        "ui-ux": {
            "name": "تصميم واجهات المستخدم",
            "keywords": [
                "ui", "ux", "figma", "sketch", "adobe-xd",
                "prototype", "wireframe", "mockup", "user-flow",
                "user-research", "design-system", "component-library", "accessibility-design",
                "interaction-design", "user-journey", "information-architecture"
            ]
        },
        "visual": {
            "name": "التصميم البصري",
            "keywords": [
                "graphic", "visual", "brand", "branding", "logo", "typography",
                "illustrator", "photoshop", "affinity", "canva", "print",
                "color-theory", "layout", "grid", "visual-hierarchy"
            ]
        },
        "motion": {
            "name": "الحركة والأنيميشن",
            "keywords": [
                "animation", "motion-design", "gsap", "lottie",
                "after-effects", "framer-motion", "micro-interaction",
                "css-animation", "transition"
            ]
        },
        "design-tools": {
            "name": "أدوات التصميم",
            "keywords": [
                "design-tools", "design-software", "creative-tools",
                "product-design", "service-design"
            ]
        }
    },
    "Data": {
        "analytics": {
            "name": "التحليلات والذكاء التجاري",
            "keywords": [
                "analytics", "bi", "tableau", "powerbi", "looker", "metabase",
                "data-visualization", "reporting", "a-b-testing", "funnel",
                "google-analytics", "amplitude", "mixpanel"
            ]
        },
        "engineering": {
            "name": "هندسة البيانات",
            "keywords": [
                "etl", "elt", "data-pipeline", "warehouse",
                "airflow", "kafka", "spark", "bigquery", "snowflake", "dbt", "data-lake",
                "data-ops", "data-integration", "streaming"
            ]
        },
        "data-science": {
            "name": "علم البيانات",
            "keywords": [
                "data-science", "pandas", "numpy", "matplotlib", "seaborn",
                "plotly", "jupyter", "notebook", "statistical-modeling",
                "scipy", "scikit-learn-data", "eda"
            ]
        },
        "seo": {
            "name": "تحسين محركات البحث",
            "keywords": [
                "seo", "metadata", "add-seo", "metadata-api",
                "schema-markup", "sitemap", "keyword-research",
                "seo-audit", "seo-analysis", "seo-optimization",
                "google-search-console", "ahrefs", "semrush"
            ]
        },
        "data-management": {
            "name": "إدارة البيانات",
            "keywords": [
                "dataset", "data-management", "dummy-data", "dummy-dataset",
                "data-quality", "scraping", "web-scraping",
                "data-governance", "data-lineage", "data-catalog"
            ]
        },
        "data-visualization": {
            "name": "تصور البيانات",
            "keywords": [
                "data-viz", "chart", "dashboard", "visualization",
                "d3", "chartjs", "highcharts", "apexcharts"
            ]
        }
    },
    "WordPress": {
        "plugin-development": {
            "name": "تطوير الإضافات",
            "keywords": [
                "plugin", "hooks", "wp-hooks", "shortcode", "custom-post-type", "wp-cli", "wp-cron",
                "wp-options", "wp-transient", "wp-rewrite"
            ]
        },
        "theme-development": {
            "name": "تطوير القوالب",
            "keywords": [
                "theme", "child-theme", "gutenberg", "wp-block", "fse", "elementor", "divi",
                "wp-template", "template-hierarchy", "wp-header"
            ]
        },
        "woocommerce": {
            "name": "متجر ووكومرس",
            "keywords": [
                "woocommerce", "woo", "product", "checkout", "cart-wp",
                "wc-api", "wc-hooks", "wc-settings"
            ]
        },
        "wp-api": {
            "name": "API ووردبريس",
            "keywords": [
                "wp-rest-api", "wp-interactivity", "headless-wp", "acf", "wp-graphql",
                "wp-json", "wp-api", "wp-customize-api"
            ]
        },
        "wp-security": {
            "name": "أمن ووردبريس",
            "keywords": [
                "wp-security", "wp-hardening", "wp-firewall",
                "wp-anti-spam", "wp-login-security"
            ]
        }
    },
    "Finance": {
        "trading": {
            "name": "التداول",
            "keywords": [
                "trading", "stock", "forex", "options", "futures",
                "trading-signal", "venice-crypto", "crypto-rpc", "algo-trading",
                "technical-analysis", "market-analysis"
            ]
        },
        "investment": {
            "name": "الاستثمار",
            "keywords": [
                "investment", "portfolio", "asset-management", "wealth-management", "bonds",
                "etf", "mutual-funds", "real-estate"
            ]
        },
        "payments": {
            "name": "المدفوعات",
            "keywords": [
                "stripe", "paypal", "payment-gateway", "billing", "subscription", "plaid",
                "payment-processing", "recurring-payments", "invoicing"
            ]
        },
        "accounting": {
            "name": "المحاسبة",
            "keywords": [
                "accounting", "bookkeeping", "tax", "payroll",
                "financial-reporting", "audit", "compliance"
            ]
        },
        "fintech": {
            "name": "التكنولوجيا المالية",
            "keywords": [
                "fintech", "banking", "insurance", "lending",
                "crypto-finance", "digital-banking"
            ]
        }
    },
    "Programming Languages": {
        "python": {
            "name": "بايثون",
            "keywords": [
                "python", "pip", "pyenv", "poetry", "asyncio", "pydantic",
                "python3", "venv", "conda", "jupyter-python"
            ]
        },
        "javascript": {
            "name": "جافاسكريبت",
            "keywords": [
                "javascript", "js", "ecmascript", "es6", "esm",
                "node", "npm", "yarn", "pnpm"
            ]
        },
        "typescript": {
            "name": "تايبسكريبت",
            "keywords": [
                "typescript", "ts", "tsx", "ts-node",
                "type-script", "typing"
            ]
        },
        "java": {
            "name": "جافا",
            "keywords": [
                "java", "jdk", "jvm", "maven", "gradle",
                "spring", "springboot", "hibernate", "jpa"
            ]
        },
        "rust": {
            "name": "راست",
            "keywords": [
                "rust", "rust-lang", "cargo", "crates",
                "tokio", "actix", "axum", "rocket"
            ]
        },
        "go": {
            "name": "جو / غو",
            "keywords": [
                "go", "golang", "go-lang",
                "go-fiber", "gin", "echo", "goroutine", "channel"
            ]
        },
        "cpp": {
            "name": "سي بلس بلس",
            "keywords": [
                "c++", "cpp", "cplusplus", "cmake",
                "llvm", "clang", "gcc", "makefile"
            ]
        },
        "csharp": {
            "name": "سي شارب / دوت نت",
            "keywords": [
                "c#", "csharp", "dotnet", ".net",
                "asp.net", "blazor", "entity-framework", "linq"
            ]
        },
        "ruby": {
            "name": "روبي",
            "keywords": ["ruby", "rails", "gem", "bundler", "ruby-on-rails"]
        },
        "php": {
            "name": "بي إتش بي",
            "keywords": ["php", "composer", "laravel-php", "symfony-php", "wordpress-php"]
        },
        "swift": {
            "name": "سويفت",
            "keywords": ["swift", "swiftui", "uikit", "cocoa", "xcode-swift"]
        },
        "kotlin": {
            "name": "كوتلن",
            "keywords": ["kotlin", "android-kotlin", "koltin"]
        },
        "other-languages": {
            "name": "لغات أخرى",
            "keywords": [
                "scala", "elixir", "haskell", "clojure", "erlang",
                "dart", "lua", "julia", "zig", "nim", "crystal"
            ]
        }
    },
    "Databases": {
        "sql": {
            "name": "قواعد بيانات علائقية",
            "keywords": [
                "sql", "postgres", "postgresql", "mysql", "mariadb", "sqlite",
                "orm", "prisma", "drizzle", "sequelize", "typeorm",
                "migration", "schema", "query-optimization", "index",
                "transactions", "acid", "stored-procedures"
            ]
        },
        "nosql": {
            "name": "NoSQL",
            "keywords": [
                "mongodb", "mongoose", "dynamodb", "couchdb", "cassandra",
                "scylladb", "document-db", "key-value"
            ]
        },
        "redis": {
            "name": "ريديس والتخزين المؤقت",
            "keywords": [
                "redis", "valkey", "memcached", "pub-sub-redis",
                "redis-cluster", "redis-cache"
            ]
        },
        "firebase": {
            "name": "فايربيس",
            "keywords": [
                "firebase", "firestore", "realtime-database",
                "firebase-auth", "firebase-basics", "remote-config",
                "apk-scanner", "firebase-functions"
            ]
        },
        "supabase": {
            "name": "سوبابيس",
            "keywords": [
                "supabase", "supabase-auth", "supabase-storage",
                "supabase-realtime", "supabase-db"
            ]
        },
        "analytics-db": {
            "name": "قواعد بيانات التحليلات",
            "keywords": [
                "duckdb", "clickhouse", "timescaledb", "influxdb",
                "columnar", "olap", "data-warehouse"
            ]
        },
        "vector-db": {
            "name": "قواعد البيانات المتجهية",
            "keywords": [
                "pinecone", "weaviate", "chroma", "qdrant",
                "milvus", "pgvector", "vector-database"
            ]
        },
        "graph-db": {
            "name": "قواعد بيانات الرسم البياني",
            "keywords": ["neo4j", "arangodb", "graph-database", "cypher"]
        }
    },
    "Cloud & Infrastructure": {
        "aws": {
            "name": "أمازون ويب سيرفيسز",
            "keywords": [
                "aws", "ec2", "s3", "rds", "lambda", "cloudfront",
                "sqs", "sns", "iam", "vpc", "eks", "ecs", "amplify", "cognito",
                "aws-cli", "aws-sdk", "cloudformation"
            ]
        },
        "azure": {
            "name": "مايكروسوفت أزور",
            "keywords": [
                "azure", "azure-functions", "azure-blob", "azure-devops", "azure-ad",
                "azure-cli", "azure-sdk", "azure-storage"
            ]
        },
        "gcp": {
            "name": "جوجل كلاود",
            "keywords": [
                "gcp", "google cloud", "google-cloud", "cloud-run",
                "gke", "cloud-functions", "bigquery-gcp",
                "gcloud", "google-apis"
            ]
        },
        "cloudflare": {
            "name": "كلاودفلير",
            "keywords": [
                "cloudflare", "cloudflare-workers", "r2", "d1",
                "workers-kv", "durable-objects", "pages-cf",
                "cloudflare-email", "cloudflare-tunnel"
            ]
        },
        "hosting": {
            "name": "الاستضافة والنشر",
            "keywords": [
                "netlify", "netlify-caching", "edge-functions", "netlify-edge",
                "vercel", "railway", "render", "fly.io",
                "heroku", "digital-ocean", "linode", "hetzner", "vps"
            ]
        },
        "serverless": {
            "name": "السيرفرليس والحافة",
            "keywords": [
                "serverless", "edge", "cdn", "function-as-a-service",
                "clickhouse-cloud", "clickhousectl"
            ]
        },
        "general-cloud": {
            "name": "سحابة عامة",
            "keywords": [
                "cloud-general", "cloud-computing", "iaas", "paas", "saas",
                "multi-cloud", "hybrid-cloud"
            ]
        }
    },
    "Security": {
        "authentication": {
            "name": "المصادقة والهوية",
            "keywords": [
                "authentication", "authorization", "auth0", "clerk",
                "jwt", "oauth", "oauth2", "oidc", "saml", "sso",
                "firebase-auth", "supabase-auth", "keycloak", "mfa", "2fa",
                "passwordless", "webauthn", "passkeys"
            ]
        },
        "application-security": {
            "name": "أمان التطبيقات",
            "keywords": [
                "cors", "csrf", "xss", "sql-injection", "owasp",
                "input-validation", "rate-limiting", "security-headers",
                "secure-coding", "vulnerability-scanner"
            ]
        },
        "infrastructure-security": {
            "name": "أمان البنية التحتية",
            "keywords": [
                "encryption", "hashing", "tls", "ssl", "certificate",
                "secrets-management", "vault", "zero-trust",
                "ids", "ips", "siem", "security-monitoring"
            ]
        },
        "penetration": {
            "name": "اختبار الاختراق",
            "keywords": [
                "penetration", "pentest", "ctf", "exploit",
                "vulnerability", "audit", "bug-bounty",
                "kali", "metasploit", "burpsuite", "nmap"
            ]
        },
        "general-security": {
            "name": "أمن عام",
            "keywords": [
                "detecting", "detection", "hunting", "threat-hunting",
                "analysis", "investigation", "forensics", "digital-forensics",
                "incident", "incident-response", "soc", "security-operations",
                "threat-intelligence", "cti", "ioc", "indicator-of-compromise",
                "malware", "ransomware", "phishing", "spoofing",
                "security-compliance", "gdpr", "hipaa", "pci-dss",
                "security-research", "cve", "vulnerability-assessment",
                "security-best-practices", "security-architecture"
            ]
        }
    },
    "Game Development": {
        "unity": {
            "name": "يونيتي",
            "keywords": [
                "unity", "unity3d", "monobehaviour", "unity-ecs",
                "unity-ui", "unity-ai", "unity-physics"
            ]
        },
        "unreal": {
            "name": "أنريل إنجين",
            "keywords": [
                "unreal", "ue4", "ue5", "blueprint", "nanite", "lumen",
                "unreal-c++", "unreal-umg"
            ]
        },
        "godot": {
            "name": "غودو",
            "keywords": ["godot", "gdscript", "godot4", "godot-engine"]
        },
        "web-games": {
            "name": "ألعاب الويب",
            "keywords": [
                "webgl", "threejs", "three.js", "babylon.js",
                "phaser", "canvas", "pixi.js", "playcanvas"
            ]
        },
        "game-design": {
            "name": "تصميم الألعاب",
            "keywords": [
                "game-design", "game-mechanics", "north-star", "game-metrics",
                "multiplayer", "netcode", "game-server", "gaming",
                "level-design", "game-balance", "game-economy"
            ]
        }
    },
    "Networking": {
        "protocols": {
            "name": "البروتوكولات",
            "keywords": [
                "tcp", "udp", "ip", "ipv4", "ipv6",
                "http", "http2", "http3", "dns", "ftp", "smtp",
                "tls", "ssl", "quic"
            ]
        },
        "realtime": {
            "name": "الاتصال الفوري",
            "keywords": [
                "websocket", "webrtc", "socket", "socket.io",
                "sse", "long-polling"
            ]
        },
        "infrastructure": {
            "name": "بنية الشبكات",
            "keywords": [
                "routing", "firewall", "vpn", "proxy", "load-balancer",
                "reverse-proxy", "service-mesh", "istio",
                "vlan", "subnetting", "nat", "dhcp"
            ]
        },
        "security-net": {
            "name": "أمن الشبكات",
            "keywords": [
                "network-security", "packet-analysis", "wireshark",
                "ids-network", "ips-network", "zeek"
            ]
        }
    },
    "General Skills": {
        "writing": {
            "name": "الكتابة والتحرير",
            "keywords": ["writing", "copywriting", "edit", "prose", "grammar", "unslop", "voice"]
        },
        "research": {
            "name": "البحث الأكاديمي",
            "keywords": ["research", "paper", "scientific", "literature", "peer-review", "citation", "experiment", "hypothesis"]
        },
        "product-management": {
            "name": "إدارة المنتجات",
            "keywords": ["product", "pm", "roadmap", "prd", "user-story", "strategy", "discovery", "prioritization"]
        },
        "leadership": {
            "name": "القيادة والإدارة",
            "keywords": ["leadership", "management", "executive", "strategy", "planning", "decision-making"]
        },
        "education": {
            "name": "التعليم والتدريب",
            "keywords": ["education", "training", "teaching", "learning", "tutorial", "curriculum"]
        }
    },
    "Marketing": {
        "marketing-general": {
            "name": "تسويق عام",
            "keywords": ["marketing", "brand", "campaign", "funnel", "conversion", "seo", "social-media", "content"]
        }
    }
}

# ============================================================
# 🔧 Technology/Framework Detection
# ============================================================

TECH_STACKS = {
    # ========== المهارات العامة ==========
    "writing": {
        "keywords": [
            "writing", "copywriting", "copy-editing", "prose", "beautiful-prose",
            "edit-article", "grammar-check", "de-ai-ify", "unslop",
            "brand-copywriter", "cold-email", "cover-letter", "resume",
            "essay", "article", "blog", "content", "storytelling",
            "voice-extractor", "voice-checker"
        ],
        "category": "General Skills",
        "subcategory": "writing"
    },
    
    "research": {
        "keywords": [
            "research", "literature", "paper", "scientific", "academic",
            "peer-review", "citation-audit", "novelty-check", "kill-argument",
            "research-review", "research-refine", "research-grants",
            "brainstorming-research", "creative-thinking", "hypothesis-generation",
            "experiment-plan", "result-to-claim", "ablation-planner",
            "scholar-evaluation", "scientific-writing", "systematic-debugging"
        ],
        "category": "General Skills",
        "subcategory": "research"
    },
    
    "product-management": {
        "keywords": [
            "product", "pm", "product-manager", "product-strategy",
            "roadmap", "prd", "user-story", "jobs-to-be-done",
            "customer-research", "discovery", "prioritization",
            "positioning", "go-to-market", "gtm", "lean-canvas",
            "business-model", "swot-analysis", "competitive-analysis",
            "north-star-metric", "okr", "metric", "dashboard"
        ],
        "category": "General Skills",
        "subcategory": "product-management"
    },
    
    "design-thinking": {
        "keywords": [
            "design-thinking", "design-sprint", "prototype",
            "user-research", "user-journey", "customer-journey",
            "empathy", "ideation", "brainstorm", "workshop"
        ],
        "category": "Design",
        "subcategory": "design-thinking"
    },
    
    "marketing": {
        "keywords": [
            "marketing", "marketing-strategy", "content-marketing",
            "social-media", "seo", "sem", "email-marketing",
            "brand", "branding", "positioning", "messaging",
            "campaign", "funnel", "conversion", "cro",
            "analytics-marketing", "attribution", "a-b-testing"
        ],
        "category": "Marketing",
        "subcategory": "marketing-general"
    },
    
    "accounting": {
        "keywords": [
            "accounting", "bookkeeping", "tax", "payroll",
            "financial-reporting", "audit", "compliance",
            "ifrs", "gaap", "revenue", "expense",
            "freelance-intake", "return-assembly", "workflow-base",
            "corporate-tax", "vat", "gst", "crypto-tax"
        ],
        "category": "Finance",
        "subcategory": "accounting"
    },
    
    "security-general": {
        "keywords": [
            "detecting", "hunting", "forensics", "incident-response",
            "threat-intelligence", "ioc", "malware-analysis",
            "vulnerability-assessment", "penetration-test",
            "security-audit", "compliance", "gdpr",
            "analyzing", "investigating", "performing"
        ],
        "category": "Security",
        "subcategory": "security-operations"
    },
    
    "software-engineering": {
        "keywords": [
            "software-engineering", "software-design", "architecture",
            "design-patterns", "refactoring", "code-quality",
            "tdd", "test-driven", "unit-test", "integration-test",
            "code-review", "code-deduplication", "code-graph",
            "system-design", "microservices", "api-design"
        ],
        "category": "Programming Languages",
        "subcategory": "software-engineering"
    },
    
    "leadership": {
        "keywords": [
            "leadership", "management", "team", "coordination",
            "executive", "director", "strategy", "planning",
            "decision-making", "communication", "negotiation"
        ],
        "category": "General Skills",
        "subcategory": "leadership"
    },
    
    "education": {
        "keywords": [
            "education", "training", "tutorial", "learning",
            "teaching", "curriculum", "skill-development"
        ],
        "category": "General Skills",
        "subcategory": "education"
    },
    
    # ========== Web Development - Backend ==========
    "laravel": {"keywords": ["laravel", "eloquent", "blade", "artisan", "php artisan"], "category": "Web Development", "subcategory": "backend"},
    "django": {"keywords": ["django", "django-rest", "django-admin", "django-orm"], "category": "Web Development", "subcategory": "backend"},
    "express": {"keywords": ["express", "expressjs", "express.js"], "category": "Web Development", "subcategory": "backend"},
    "spring": {"keywords": ["spring", "spring-boot", "spring-mvc", "spring-data"], "category": "Web Development", "subcategory": "backend"},
    "nodejs": {"keywords": ["nodejs", "node.js", "node", "npm", "yarn"], "category": "Web Development", "subcategory": "backend"},
    "fastapi": {"keywords": ["fastapi", "fast-api", "python api"], "category": "Web Development", "subcategory": "backend"},
    "flask": {"keywords": ["flask", "python flask", "flask-api"], "category": "Web Development", "subcategory": "backend"},
    "rails": {"keywords": ["rails", "ruby-on-rails", "ruby on rails"], "category": "Web Development", "subcategory": "backend"},
    "aspnet": {"keywords": ["asp.net", "aspnet", "dotnet", ".net"], "category": "Web Development", "subcategory": "backend"},
    "nestjs": {"keywords": ["nestjs", "nest.js", "nest-js"], "category": "Web Development", "subcategory": "backend"},
    
    # ========== Web Development - Frontend ==========
    "react": {"keywords": ["react", "reactjs", "react.js", "react-app"], "category": "Web Development", "subcategory": "frontend"},
    "vue": {"keywords": ["vue", "vuejs", "vue.js", "vue-app"], "category": "Web Development", "subcategory": "frontend"},
    "angular": {"keywords": ["angular", "angularjs", "angular.js", "ng", "ngx"], "category": "Web Development", "subcategory": "frontend"},
    "nextjs": {"keywords": ["nextjs", "next.js", "next-app", "next-js"], "category": "Web Development", "subcategory": "frontend"},
    "svelte": {"keywords": ["svelte", "sveltejs", "svelte.js"], "category": "Web Development", "subcategory": "frontend"},
    "astro": {"keywords": ["astro", "astrojs", "astro.js"], "category": "Web Development", "subcategory": "frontend"},
    "tailwind": {"keywords": ["tailwind", "tailwindcss", "tailwind-css"], "category": "Web Development", "subcategory": "frontend"},
    "bootstrap": {"keywords": ["bootstrap", "bootstrap-5", "bs4"], "category": "Web Development", "subcategory": "frontend"},
    
    # ========== Web Development - Testing ==========
    "playwright": {"keywords": ["playwright", "playwright-test"], "category": "Web Development", "subcategory": "testing-web"},
    "cypress": {"keywords": ["cypress", "cypress-test"], "category": "Web Development", "subcategory": "testing-web"},
    "jest": {"keywords": ["jest", "jest-test"], "category": "Web Development", "subcategory": "testing-web"},
    "vitest": {"keywords": ["vitest", "vitest-test"], "category": "Web Development", "subcategory": "testing-web"},
    
    # ========== Mobile Development ==========
    "flutter": {"keywords": ["flutter", "dart", "flutter-app", "flutter-widget"], "category": "Mobile Development", "subcategory": "flutter"},
    "react-native": {"keywords": ["react-native", "react native", "rn", "expo"], "category": "Mobile Development", "subcategory": "react-native"},
    "android": {"keywords": ["android", "kotlin", "android-studio", "gradle", "apk"], "category": "Mobile Development", "subcategory": "android"},
    "ios": {"keywords": ["ios", "swift", "xcode", "cocoa", "objc"], "category": "Mobile Development", "subcategory": "ios"},
    "ionic": {"keywords": ["ionic", "capacitor", "cordova"], "category": "Mobile Development", "subcategory": "cross-platform"},
    "appium": {"keywords": ["appium", "mobile-testing"], "category": "Mobile Development", "subcategory": "mobile-testing"},
    
    # ========== AI & Machine Learning ==========
    "tensorflow": {"keywords": ["tensorflow", "tf", "keras"], "category": "AI & Machine Learning", "subcategory": "ml-models"},
    "pytorch": {"keywords": ["pytorch", "torch", "torchvision", "torchaudio"], "category": "AI & Machine Learning", "subcategory": "ml-models"},
    "scikit-learn": {"keywords": ["scikit-learn", "sklearn", "scikit"], "category": "AI & Machine Learning", "subcategory": "ml-models"},
    "langchain": {"keywords": ["langchain", "lang-chain"], "category": "AI & Machine Learning", "subcategory": "ai-agents"},
    "llamaindex": {"keywords": ["llamaindex", "llama-index"], "category": "AI & Machine Learning", "subcategory": "ai-agents"},
    "openai": {"keywords": ["openai", "gpt", "chatgpt", "gpt-4", "gpt-5"], "category": "AI & Machine Learning", "subcategory": "llm-models"},
    "anthropic": {"keywords": ["anthropic", "claude", "haiku", "sonnet"], "category": "AI & Machine Learning", "subcategory": "llm-models"},
    "llama": {"keywords": ["llama", "llama2", "llama-2", "meta-llama", "llama3"], "category": "AI & Machine Learning", "subcategory": "llm-models"},
    "huggingface": {"keywords": ["huggingface", "hugging-face", "transformers"], "category": "AI & Machine Learning", "subcategory": "ai-tools"},
    "composio": {"keywords": ["composio", "composio-ai"], "category": "AI & Machine Learning", "subcategory": "ai-agents"},
    "autogen": {"keywords": ["autogen", "microsoft-autogen"], "category": "AI & Machine Learning", "subcategory": "ai-agents"},
    "crewai": {"keywords": ["crewai", "crew-ai"], "category": "AI & Machine Learning", "subcategory": "ai-agents"},
    "dspy": {"keywords": ["dspy", "stanford-dspy"], "category": "AI & Machine Learning", "subcategory": "ai-agents"},
    "gemini": {"keywords": ["gemini", "google-gemini"], "category": "AI & Machine Learning", "subcategory": "llm-models"},
    "mistral": {"keywords": ["mistral", "mistral-ai"], "category": "AI & Machine Learning", "subcategory": "llm-models"},
    "deepseek": {"keywords": ["deepseek", "deep-seek"], "category": "AI & Machine Learning", "subcategory": "llm-models"},
    "fal-ai": {"keywords": ["fal-ai", "fal.ai", "fal"], "category": "AI & Machine Learning", "subcategory": "ai-tools"},
    "replicate": {"keywords": ["replicate", "replicate-ai"], "category": "AI & Machine Learning", "subcategory": "ai-tools"},
    "audiocraft": {"keywords": ["audiocraft", "musicgen", "audiogen"], "category": "AI & Machine Learning", "subcategory": "ai-tools"},
    "stable-diffusion": {"keywords": ["stable-diffusion", "diffusers", "stability-ai"], "category": "AI & Machine Learning", "subcategory": "computer-vision"},
    
    # ========== Blockchain ==========
    "ethereum": {"keywords": ["ethereum", "eth", "solidity", "web3", "erc20", "erc721"], "category": "Blockchain", "subcategory": "smart-contracts"},
    "solana": {"keywords": ["solana", "sol", "spl", "anchor"], "category": "Blockchain", "subcategory": "networks"},
    "hardhat": {"keywords": ["hardhat", "hardhat-ethereum"], "category": "Blockchain", "subcategory": "smart-contracts"},
    "foundry": {"keywords": ["foundry", "forge", "cast"], "category": "Blockchain", "subcategory": "smart-contracts"},
    "wagmi": {"keywords": ["wagmi", "wagmi-react"], "category": "Blockchain", "subcategory": "web3-frontend"},
    "viem": {"keywords": ["viem", "viem-js"], "category": "Blockchain", "subcategory": "web3-frontend"},
    "ethers": {"keywords": ["ethers", "ethers-js"], "category": "Blockchain", "subcategory": "web3-frontend"},
    "helius": {"keywords": ["helius", "helius-api"], "category": "Blockchain", "subcategory": "blockchain-tools"},
    "venice": {"keywords": ["venice", "venice-ai"], "category": "Blockchain", "subcategory": "blockchain-tools"},
    
    # ========== DevOps ==========
    "docker": {"keywords": ["docker", "container", "dockerfile", "docker-compose"], "category": "DevOps", "subcategory": "containerization"},
    "kubernetes": {"keywords": ["kubernetes", "k8s", "kubectl", "helm"], "category": "DevOps", "subcategory": "containerization"},
    "terraform": {"keywords": ["terraform", "iac", "infrastructure-as-code"], "category": "DevOps", "subcategory": "infrastructure"},
    "jenkins": {"keywords": ["jenkins", "jenkinsfile", "ci-cd"], "category": "DevOps", "subcategory": "cicd"},
    "ansible": {"keywords": ["ansible", "playbook", "ansible-playbook"], "category": "DevOps", "subcategory": "infrastructure"},
    "github-actions": {"keywords": ["github-actions", "gh-actions"], "category": "DevOps", "subcategory": "cicd"},
    "gitlab-ci": {"keywords": ["gitlab-ci", "gitlab-ci.yml"], "category": "DevOps", "subcategory": "cicd"},
    "prometheus": {"keywords": ["prometheus", "prometheus-operator"], "category": "DevOps", "subcategory": "monitoring"},
    "grafana": {"keywords": ["grafana", "grafana-dashboard"], "category": "DevOps", "subcategory": "monitoring"},
    "argocd": {"keywords": ["argocd", "argo-cd"], "category": "DevOps", "subcategory": "cicd"},
    
    # ========== Databases ==========
    "postgresql": {"keywords": ["postgres", "postgresql", "pgsql"], "category": "Databases", "subcategory": "sql"},
    "mysql": {"keywords": ["mysql", "mariadb"], "category": "Databases", "subcategory": "sql"},
    "mongodb": {"keywords": ["mongodb", "mongo", "mongoose"], "category": "Databases", "subcategory": "nosql"},
    "redis": {"keywords": ["redis", "redis-cache"], "category": "Databases", "subcategory": "redis"},
    "firebase": {"keywords": ["firebase", "firestore", "firebase-auth"], "category": "Databases", "subcategory": "firebase"},
    "supabase": {"keywords": ["supabase", "supabase-db"], "category": "Databases", "subcategory": "supabase"},
    "duckdb": {"keywords": ["duckdb", "duck-db"], "category": "Databases", "subcategory": "analytics-db"},
    "clickhouse": {"keywords": ["clickhouse", "click-house"], "category": "Databases", "subcategory": "analytics-db"},
    "pinecone": {"keywords": ["pinecone", "pinecone-io"], "category": "Databases", "subcategory": "vector-db"},
    "qdrant": {"keywords": ["qdrant", "qdrant-db"], "category": "Databases", "subcategory": "vector-db"},
    "prisma": {"keywords": ["prisma", "prisma-orm"], "category": "Databases", "subcategory": "sql"},
    "drizzle": {"keywords": ["drizzle", "drizzle-orm"], "category": "Databases", "subcategory": "sql"},
    
    # ========== Cloud & Infrastructure ==========
    "aws": {"keywords": ["aws", "ec2", "s3", "lambda", "dynamodb", "cloudfront"], "category": "Cloud & Infrastructure", "subcategory": "aws"},
    "azure": {"keywords": ["azure", "azure-devops", "microsoft-azure"], "category": "Cloud & Infrastructure", "subcategory": "azure"},
    "gcp": {"keywords": ["gcp", "google-cloud", "gcloud"], "category": "Cloud & Infrastructure", "subcategory": "gcp"},
    "cloudflare": {"keywords": ["cloudflare", "cloudflare-workers", "cf-workers"], "category": "Cloud & Infrastructure", "subcategory": "cloudflare"},
    "netlify": {"keywords": ["netlify", "netlify-functions"], "category": "Cloud & Infrastructure", "subcategory": "hosting"},
    "vercel": {"keywords": ["vercel", "vercel-deploy"], "category": "Cloud & Infrastructure", "subcategory": "hosting"},
    
    # ========== Programming Languages ==========
    "python": {"keywords": ["python", "py", "python3"], "category": "Programming Languages", "subcategory": "python"},
    "javascript": {"keywords": ["javascript", "js", "ecmascript"], "category": "Programming Languages", "subcategory": "javascript"},
    "typescript": {"keywords": ["typescript", "ts", "tsx"], "category": "Programming Languages", "subcategory": "typescript"},
    "java": {"keywords": ["java", "jdk", "jvm"], "category": "Programming Languages", "subcategory": "java"},
    "rust": {"keywords": ["rust", "rust-lang"], "category": "Programming Languages", "subcategory": "rust"},
    "go": {"keywords": ["go", "golang", "go-lang"], "category": "Programming Languages", "subcategory": "go"},
    "cpp": {"keywords": ["c++", "cpp", "cplusplus"], "category": "Programming Languages", "subcategory": "cpp"},
    "csharp": {"keywords": ["c#", "csharp", "dotnet"], "category": "Programming Languages", "subcategory": "csharp"},
    "ruby": {"keywords": ["ruby", "ruby-lang"], "category": "Programming Languages", "subcategory": "ruby"},
    "php": {"keywords": ["php", "php8"], "category": "Programming Languages", "subcategory": "php"},
    "swift": {"keywords": ["swift", "swift-lang"], "category": "Programming Languages", "subcategory": "swift"},
    "kotlin": {"keywords": ["kotlin", "kotlin-lang"], "category": "Programming Languages", "subcategory": "kotlin"},
    
    # ========== Design ==========
    "figma": {"keywords": ["figma", "figma-design"], "category": "Design", "subcategory": "ui-ux"},
    "gsap": {"keywords": ["gsap", "green-sock"], "category": "Design", "subcategory": "motion"},
    
    # ========== Finance ==========
    "stripe": {"keywords": ["stripe", "stripe-payment"], "category": "Finance", "subcategory": "payments"},
    "paypal": {"keywords": ["paypal", "paypal-payment"], "category": "Finance", "subcategory": "payments"},
    
    # ========== Game Development ==========
    "unity": {"keywords": ["unity", "unity3d"], "category": "Game Development", "subcategory": "unity"},
    "unreal": {"keywords": ["unreal", "ue4", "ue5"], "category": "Game Development", "subcategory": "unreal"},
    "godot": {"keywords": ["godot", "godot-engine"], "category": "Game Development", "subcategory": "godot"},
    "threejs": {"keywords": ["threejs", "three.js"], "category": "Game Development", "subcategory": "web-games"},
    
    # ========== Security ==========
    "auth0": {"keywords": ["auth0", "auth0-sdk"], "category": "Security", "subcategory": "authentication"},
    "clerk": {"keywords": ["clerk", "clerk-auth"], "category": "Security", "subcategory": "authentication"},
    "sentry": {"keywords": ["sentry", "sentry-io"], "category": "Security", "subcategory": "monitoring-security"},
    "keycloak": {"keywords": ["keycloak", "keycloak-auth"], "category": "Security", "subcategory": "authentication"},
    
    # ========== WordPress ==========
    "wordpress": {"keywords": ["wordpress", "wp", "wordpress-dev"], "category": "WordPress", "subcategory": "plugin-development"},
    "woocommerce": {"keywords": ["woocommerce", "woo"], "category": "WordPress", "subcategory": "woocommerce"}
}

# ============================================================
# 🔧 Helper Functions
# ============================================================

def slugify(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\-_]+', '-', text)
    text = re.sub(r'-+', '-', text)
    if len(text) > 80:
        text = text[:80]
        text = text.rstrip('-')
    return text.strip('-')


def extract_skill_name(content, fallback_name):
    match = re.search(r'^name:\s*(.+)$', content, re.MULTILINE)
    if match:
        name = match.group(1).strip()
        name = re.sub(r'\s*\(\d+\)\s*$', '', name)
        return name
    lines = content.split('\n')
    for line in lines[:20]:
        line = line.strip()
        if not line or line.startswith('#') or line.startswith('```') or line.startswith('---'):
            continue
        clean_name = re.sub(r'^#\s*', '', line)
        clean_name = re.sub(r'\s*\(skill\)$', '', clean_name, flags=re.IGNORECASE)
        clean_name = re.sub(r'\s*\(\d+\)\s*$', '', clean_name)
        if clean_name and len(clean_name) > 3:
            return clean_name.strip()
    clean_name = re.sub(r'^SKILL\s*\(?\d+\)?\s*-\s*', '', fallback_name)
    clean_name = re.sub(r'\s*\(\d+\)\s*$', '', clean_name)
    clean_name = re.sub(r'^SKILL\s+', '', clean_name)
    clean_name = re.sub(r'^SKILL-', '', clean_name)
    if clean_name and clean_name != fallback_name:
        return clean_name.strip()
    return fallback_name


def extract_description(content):
    match = re.search(r'^description:\s*(.+)$', content, re.MULTILINE | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    lines = content.split('\n')
    for i, line in enumerate(lines):
        if re.search(r'^#+\s*(description|overview|about|summary)', line, re.IGNORECASE):
            if i + 1 < len(lines) and lines[i + 1].strip():
                return lines[i + 1].strip()
    return ""


def detect_main_category(text, skill_name=""):
    text_lower = text.lower()
    skill_lower = skill_name.lower()
    scores = {}
    for category, keywords in MAIN_CATEGORY_KEYWORDS.items():
        score = 0
        for keyword in keywords:
            if keyword.lower() in skill_lower:
                score += 5
            score += text_lower.count(keyword.lower()) * 2
        if score > 0:
            scores[category] = score
    if not scores:
        return None
    return max(scores, key=scores.get)


def detect_sub_category(text, main_category, skill_name=""):
    if not main_category or main_category not in SUB_CATEGORIES:
        return None
    text_lower = text.lower()
    skill_lower = skill_name.lower()
    sub_categories = SUB_CATEGORIES[main_category]
    scores = {}
    for sub_id, sub_data in sub_categories.items():
        score = 0
        for keyword in sub_data["keywords"]:
            if keyword.lower() in skill_lower:
                score += 5
            score += text_lower.count(keyword.lower()) * 2
        if score > 0:
            scores[sub_id] = score
    if not scores:
        return None
    return max(scores, key=scores.get)


def detect_technology(text, main_category, sub_category, skill_name=""):
    """
    Detect the specific technology/framework from the content.
    Returns: technology name or "general" if not found.
    Path structure: maincategory / subcategory / technology
    """
    text_lower = text.lower()
    skill_lower = skill_name.lower()
    scores = {}
    for tech_name, tech_data in TECH_STACKS.items():
        if tech_data["category"] != main_category:
            continue
        if tech_data["subcategory"] != sub_category:
            continue
        score = 0
        for keyword in tech_data["keywords"]:
            keyword_lower = keyword.lower()
            if keyword_lower in skill_lower:
                score += 10
            score += text_lower.count(keyword_lower) * 3
        if score > 0:
            scores[tech_name] = score
    if not scores:
        return "general"
    return max(scores, key=scores.get)


def get_file_hash(content):
    return hashlib.sha256(content.encode('utf-8')).hexdigest()


def get_file_signature(content, file_size):
    normalized = re.sub(r'\s+', ' ', content.strip())
    content_sig = normalized[:500]
    return f"{file_size}|{content_sig}"


def get_unique_filename(base_name, full_path, output_dir, used_names):
    if len(base_name) > 60:
        base_name = base_name[:60]
    clean_name = slugify(base_name)
    if not clean_name or len(clean_name) < 2:
        clean_name = "unnamed"
    if len(clean_name) > 50:
        clean_name = clean_name[:50].rstrip('-')
    filename = clean_name + ".md"
    counter = 1
    dest_dir = output_dir / full_path
    max_attempts = 50
    while counter < max_attempts:
        filename = f"{clean_name}-{counter}.md" if counter > 1 else f"{clean_name}.md"
        full_path_check = dest_dir / filename
        if len(str(full_path_check)) > 240:
            clean_name = clean_name[:30].rstrip('-')
            filename = f"{clean_name}-{counter}.md"
            full_path_check = dest_dir / filename
        if not (dest_dir / filename).exists() and filename not in used_names:
            break
        counter += 1
    if counter >= max_attempts:
        import time
        filename = f"skill-{int(time.time())}.md"
        while (dest_dir / filename).exists() or filename in used_names:
            import time
            filename = f"skill-{int(time.time())}.md"
    used_names.add(filename)
    return filename


def load_existing_data():
    if DATA_FILE.exists():
        try:
            with open(DATA_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            return None
    return None


def load_existing_signatures():
    if SIGNATURES_FILE.exists():
        try:
            with open(SIGNATURES_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            return {}
    return {}


def save_signatures(signatures):
    with open(SIGNATURES_FILE, "w", encoding="utf-8") as f:
        json.dump(signatures, f, ensure_ascii=False, indent=2)


def get_existing_files():
    existing_hashes = set()
    signatures = load_existing_signatures()
    existing_hashes.update(signatures.keys())
    if OUTPUT_DIR.exists():
        for md_file in OUTPUT_DIR.rglob("*.md"):
            try:
                content = md_file.read_text(encoding="utf-8", errors="ignore")
                file_hash = get_file_hash(content)
                existing_hashes.add(file_hash)
            except:
                pass
    return existing_hashes


def log_unclassified_file(file_name, skill_name, reason, details="", main_category="", sub_category="", technology=""):
    try:
        with open(UNCLASSIFIED_FILE, "a", encoding="utf-8") as f:
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            f.write(f"\n## 📄 {file_name}\n")
            f.write(f"- **⏰ Date**: {timestamp}\n")
            f.write(f"- **🏷️ Skill Name**: {skill_name}\n")
            f.write(f"- **⚠️ Classification Issue**: {reason}\n")
            if main_category:
                f.write(f"- **📂 Proposed Category**: {main_category}\n")
            if sub_category:
                f.write(f"- **📁 Proposed Sub-category**: {sub_category}\n")
            if technology:
                f.write(f"- **🔧 Proposed Technology**: {technology}\n")
            if details:
                f.write(f"- **📝 Additional Details**: {details}\n")
            f.write(f"- **💡 Required Action**: Please review and classify this file manually\n")
            f.write("---\n")
    except Exception as e:
        print(Fore.RED + f"Error logging unclassified file: {e}")


# ============================================================
# 📄 Process a Single File — 3-level path
# ============================================================

def process_file(md_file, output_dir, existing_hashes, used_names, signatures):
    """
    Process a single markdown file and copy it to the correct folder.
    Folder structure: output_dir / main_category / sub_category / technology / filename.md
    """
    try:
        content = md_file.read_text(encoding="utf-8", errors="ignore")
        file_hash = get_file_hash(content)

        # Skip duplicates
        if file_hash in existing_hashes:
            return None, "duplicate"

        file_size = md_file.stat().st_size
        sig = get_file_signature(content, file_size)

        skill_name = extract_skill_name(content, md_file.stem)
        description = extract_description(content)

        if not skill_name:
            skill_name = md_file.stem

        main_category = detect_main_category(content, skill_name)

        if not main_category:
            log_unclassified_file(
                md_file.name, skill_name,
                lang.get('no_category_found'),
                details=content[:200]
            )
            return None, "no_category"

        sub_category = detect_sub_category(content, main_category, skill_name)

        if not sub_category:
            log_unclassified_file(
                md_file.name, skill_name,
                lang.get('no_subcategory_found', main_category),
                main_category=main_category,
                details=content[:200]
            )
            return None, "no_subcategory"

        # 🔧 Detect the specific technology/framework
        technology = detect_technology(content, main_category, sub_category, skill_name)

        # Build the 3-level path: main / sub / technology
        folder_path = Path(main_category) / sub_category / technology

        filename = get_unique_filename(skill_name, folder_path, output_dir, used_names)
        dest_dir = output_dir / folder_path
        dest_dir.mkdir(parents=True, exist_ok=True)

        dest_path = dest_dir / filename
        shutil.copy2(md_file, dest_path)

        # Save signature
        signatures[file_hash] = {
            "filename": filename,
            "path": str(folder_path / filename),
            "skill_name": skill_name,
            "technology": technology
        }
        existing_hashes.add(file_hash)

        return {
            "skill_name": skill_name,
            "description": description,
            "main_category": main_category,
            "sub_category": sub_category,
            "technology": technology,
            "file_path": str(folder_path / filename)
        }, "success"

    except Exception as e:
        print(Fore.RED + lang.get('error_processing', md_file.name, str(e)))
        return None, "error"